### ISSUE TITLE
Positioning of Label in Demo seems broken

### ISSUE THREAD

**Issue by matobeag** [CodyHouse/cd-floating-label-changelog#1]
When entering a field, the label positioning seems a bit off in the demo
https://codyhouse.co/ds/components/app/floating-label

**Comment by sebastiano-guerriero** [comment]
Hi! It seems ok on our end https://www.dropbox.com/s/wixswye105gmnbf/Screenshot%202020-12-17%20at%2010.04.56.png?dl=0

Can you please share a screenshot? Also, have you updated the `.form-label` using the Forms editor?

**Comment by matobeag** [comment]
Ah damn, sorry it's completely my fault. I changed some margins in the Global Form Settings :)

**Comment by sebastiano-guerriero** [comment]
No prob at all! Actually, I'll update the component to make sure it's no longer affected by the "default" margins of the `.form-label`. 

Cheers :)
